### PR TITLE
german graphtheory complete

### PR DESCRIPTION
**Pull request by matheharry**

### CODE REVIEW

**Comment by plegner** [comment]
Thanks, @matheharry! You can remove the `> translated: auto` lines after reviewing a section, which will hide the translation warnings for that chapter

**Comment by matheharry** [comment]
@plegner Unfortunately it is not possible to translate a paragraph directly, because it is inserted via the function salesman2. Here is a version of the function as it should be in German - maybe you have an idea how to insert it somehow.

`export function salesman2($section: Step) {
  $section.model.tsmString = (x: number) => {
    const a = [`Es gibt <strong>${x}</strong> Auswahlmöglichkeiten für die erste Stadt.`];
    if (x > 2) a.push(
        `Nachdem du die erste Stadt ausgewählt hast, gibt es nur noch <strong>${x -
                                                                1}</strong> Auswahlmöglichkeiten für die zweite Stadt.`);
    for (let i = 3; i < Math.min(6, x); ++i) a.push(
        `Danach gibt es <strong>${x - i +
                                  1}</strong> Auswahlmöglichkeiten für die ${toOrdinal(
            i)} Stadt.`);
    if (x > 6) a.push('&hellip;');
    a.push(
        `Schließlich gibt es nur noch <strong>1</strong> Auswahl für die ${toOrdinal(
            x)} Stadt.`);

    return '<li style="margin-bottom: 0">' +
           a.join('</li><li style="margin-bottom: 0">') + '</li>';
  };

  $section.model.tsnPaths = (x: number) => {
    return list(x, 1).join(' × ') + ' = ' + numberFormat(factorial(x));
  };
}`

Of course there is a little problem with the function toOrdinal. A solution could be to write a dot after the number for all languages except English, so 1st → 1., 2nd → 2. ...

**Comment by plegner** [comment]
Thanks, Harald! This is quite an old course, and we should no longer use text generated within JS for precisely this reason. This is going to take a bit of work to fix – for now, we could just have a "static" list in the German version, i.e. we pick a number and write out the bullet points without a slider…

**Comment by matheharry** [comment]
Thank you Philipp,
I'll make these changes! I really love these sliders though ...

Philipp Legner <notifications@github.com> schrieb am Sa., 25. Juli 2020,
12:44:

**Pull request merged**
